// GENERATO da ~/.tsv-work/FV-AFFITTI/tools/nota-ai.py dal LEGGIMI della consegna foto (registro foto per foto).
// Non modificare a mano: si corregge il registro e si rilancia. Mai una frase che il registro non provi.
import type { Lingua, SlugCasa } from "./case";

export const NOTA_AI: Record<SlugCasa, Record<Lingua, string[]>> = {
 "top-hill-cottage": {
  "it": [],
  "en": [],
  "de": [],
  "sl": []
 },
 "chalet-navauce": {
  "it": [
   "Le 30 fotografie di questa pagina vengono da due fonti: 15 da scatti fatti con un telefono fra il 25 maggio e il 17 giugno 2023 (date lette dai dati dello scatto) e 15 da immagini già pubblicate online in passato, piccole (da 720 a 1.200 pixel di lato) e senza dati di scatto. 24 delle 30 fotografie sono state elaborate con un modello generativo di immagini (famiglia Nano Banana di Google, usato tramite la piattaforma Higgsfield); in una sola, la foto 4, la zona dei pannelli solari viene da un ingranditore a intelligenza artificiale (Bytedance, tramite Higgsfield), perché il primo modello ridisegnava l'impianto. Lo scopo è stato uno solo: dare agli interni più luce e agli esterni una luce di giorno pulita, e ingrandire le immagini piccole fino a 7 volte. In una fotografia (la 20) sono stati tolti due oggetti personali: un oggetto nero appoggiato al tavolo e una chiave sullo schienale di una sedia. Sono stati lasciati di proposito tutti gli arredi e i tessuti, le lampade com'erano (accese o spente), i quadri, gli oggetti decorativi, i fiori, gli ombrelloni e i mobili della terrazza, i materiali accatastati vicino alla casetta nella veduta aerea. Dove un oggetto è stato tolto, la parte di tovaglia e di sedia che nascondeva non è stata fotografata: l'ha ricostruita il modello, in modo plausibile. Allo stesso modo, nelle 13 immagini piccole ingrandite con l'intelligenza artificiale il dettaglio fine (venature del legno, foglie, fiori, tegole, pietre, oggetti piccoli) è ricostruito dal modello, non recuperato: a grandezza piena i dettagli minuti sono plausibili, non documentali. Non è stato modificato nient'altro: dimensioni, aperture, travi, pavimenti, arredi, recinzioni, sentiero, tetto e pannelli solari sono quelli fotografati, le vedute dalle finestre sono le stesse, la stagione è quella dello scatto (la foto 24 è d'autunno) e nella foto notturna vera (la 26) le stelle sono quelle fotografate: 12 puntini deboli aggiunti dal modello sono stati tolti. Nelle foto non sono stati individuati difetti da documentare, e nessuno è stato attenuato o nascosto: le chiazze di terra nuda nel prato sono rimaste come sono. Le ultime quattro fotografie (27–30) sono simulazioni, dichiarate sulla foto: le stesse vedute con una luce che non c'era (due sere con la luce dorata, un tramonto, una notte con le finestre accese). La casa, il terreno, gli alberi, le recinzioni e i monti sono gli stessi; cambiano la luce e il cielo, e nella notte si accendono solo le quattro finestre della facciata e il faretto che esiste sul timpano. Le altre 6 fotografie hanno avuto solo un ritocco locale di luce e colore, senza intelligenza artificiale generativa (due vedute, la 7 e la 25, sono state anche ingrandite senza intelligenza artificiale). Luce e colori sono stati corretti come in un normale ritocco fotografico. Le fotografie originali non modificate si vedono aprendo la foto e premendo «Vedi l'originale»; la visita resta l'unico riferimento per lo stato reale dello chalet."
  ],
  "en": [
   "The 30 photographs on this page come from two sources: 15 from phone shots taken between 25 May and 17 June 2023 (dates read from the shooting data) and 15 from images previously published online, small (720 to 1,200 pixels on the long side) and without shooting data. 24 of the 30 photographs were processed with a generative image model (Google's Nano Banana family, used through the Higgsfield platform); in one of them, photo 4, the area of the solar panels comes from an AI upscaler (Bytedance, through Higgsfield), because the first model redrew the array. There was a single purpose: to give the interiors more light and the exteriors clean daylight, and to enlarge the small images up to seven times. In one photograph (no. 20) two personal objects were removed: a black object resting on the table and a key on the back of a chair. All furniture and textiles were deliberately left, as were the lamps as they were (on or off), the pictures, the decorative objects, the flowers, the parasols and terrace furniture, and the materials stacked near the hut in the aerial view. Where an object was removed, the part of the tablecloth and chair it hid was not photographed: the model reconstructed it plausibly. Likewise, in the 13 small images enlarged with AI the fine detail (wood grain, leaves, flowers, roof tiles, stones, small objects) was reconstructed by the model, not recovered: at full size the minute details are plausible, not documentary. Nothing else was changed: dimensions, openings, beams, floors, furniture, fences, path, roof and solar panels are as photographed, the views from the windows are the same, the season is the one of the shot (photo 24 is in autumn), and in the real night photograph (no. 26) the stars are the photographed ones: 12 faint dots added by the model were removed. No defects to document were found in the photographs, and none was reduced or hidden: the bare patches in the meadow are as they were. The last four photographs (27–30) are simulations, declared on the image: the same views in a light that was not there (two golden evenings, a sunset, a night with the windows lit). The house, the land, the trees, the fences and the mountains are the same; the light and the sky change, and at night only the four front windows and the existing gable light are lit. The other 6 photographs received only a local light and colour adjustment, without generative AI (two views, nos. 7 and 25, were also enlarged without AI). Light and colour were corrected as in ordinary photo editing. The original unedited photographs can be seen by opening a photo and pressing “See the original”; the visit remains the only reference for the actual condition of the chalet."
  ],
  "de": [
   "Die 30 Fotos auf dieser Seite stammen aus zwei Quellen: 15 aus Handyaufnahmen vom 25. Mai bis 17. Juni 2023 (Daten aus den Aufnahmeinformationen) und 15 aus Bildern, die früher bereits online veröffentlicht waren, klein (720 bis 1.200 Pixel Kantenlänge) und ohne Aufnahmedaten. 24 der 30 Fotos wurden mit einem generativen Bildmodell bearbeitet (Nano-Banana-Familie von Google, genutzt über die Plattform Higgsfield); bei einem davon, Foto 4, stammt der Bereich der Solarmodule aus einem KI-Hochskalierer (Bytedance, über Higgsfield), weil das erste Modell die Anlage neu gezeichnet hatte. Der Zweck war ein einziger: den Innenräumen mehr Licht und den Außenaufnahmen klares Tageslicht zu geben und die kleinen Bilder bis zum Siebenfachen zu vergrößern. Auf einem Foto (Nr. 20) wurden zwei persönliche Gegenstände entfernt: ein schwarzer Gegenstand am Tisch und ein Schlüssel an einer Stuhllehne. Bewusst belassen wurden alle Möbel und Textilien, die Lampen, wie sie waren (an oder aus), Bilder, Dekoration, Blumen, Sonnenschirme und Terrassenmöbel sowie die Materialien neben der Hütte im Luftbild. Wo ein Gegenstand entfernt wurde, war der verdeckte Teil von Tischtuch und Stuhl nicht fotografiert: Das Modell hat ihn plausibel rekonstruiert. Ebenso wurde in den 13 kleinen, mit KI vergrößerten Bildern das feine Detail (Holzmaserung, Blätter, Blumen, Dachziegel, Steine, kleine Gegenstände) vom Modell rekonstruiert, nicht wiederhergestellt: In voller Größe sind die feinen Details plausibel, aber nicht dokumentarisch. Sonst wurde nichts verändert: Maße, Öffnungen, Balken, Böden, Möbel, Zäune, Weg, Dach und Solarmodule sind wie fotografiert, die Ausblicke aus den Fenstern sind dieselben, die Jahreszeit ist die der Aufnahme (Foto 24 ist im Herbst), und auf dem echten Nachtfoto (Nr. 26) sind die Sterne die fotografierten: 12 schwache, vom Modell hinzugefügte Punkte wurden entfernt. Auf den Fotos wurden keine zu dokumentierenden Mängel festgestellt, und keiner wurde abgeschwächt oder verborgen: Die kahlen Stellen in der Wiese sind geblieben. Die letzten vier Fotos (27–30) sind Simulationen und auf dem Bild als solche gekennzeichnet: dieselben Ansichten in einem Licht, das es nicht gab (zwei goldene Abende, ein Sonnenuntergang, eine Nacht mit erleuchteten Fenstern). Haus, Gelände, Bäume, Zäune und Berge sind dieselben; Licht und Himmel ändern sich, und nachts leuchten nur die vier Fenster der Vorderseite und die vorhandene Giebelleuchte. Die übrigen 6 Fotos wurden nur lokal in Licht und Farbe korrigiert, ohne generative KI (zwei Ansichten, Nr. 7 und 25, wurden zudem ohne KI vergrößert). Licht und Farben wurden wie bei einer normalen Bildbearbeitung korrigiert. Die unbearbeiteten Originalfotos sieht man, wenn man ein Foto öffnet und „Original ansehen“ drückt; die Besichtigung bleibt der einzige Maßstab für den tatsächlichen Zustand des Chalets."
  ],
  "sl": [
   "30 fotografij na tej strani izvira iz dveh virov: 15 iz posnetkov s telefonom, nastalih med 25. majem in 17. junijem 2023 (datumi iz podatkov o posnetku), in 15 iz slik, ki so bile že prej objavljene na spletu, majhne (od 720 do 1.200 slikovnih pik po daljši stranici) in brez podatkov o posnetku. 24 od 30 fotografij je bilo obdelanih z generativnim modelom za slike (Googlova družina Nano Banana, uporabljena prek platforme Higgsfield); pri eni od njih, fotografiji 4, območje sončnih panelov izvira iz povečevalnika z umetno inteligenco (Bytedance, prek Higgsfielda), ker je prvi model elektrarno narisal na novo. Namen je bil en sam: notranjim prostorom dati več svetlobe, zunanjim posnetkom čisto dnevno svetlobo in majhne slike povečati do sedemkrat. Na eni fotografiji (št. 20) sta bila odstranjena dva osebna predmeta: črn predmet na mizi in ključ na naslonjalu stola. Namenoma so ostali vse pohištvo in tekstil, svetila takšna, kot so bila (prižgana ali ugasnjena), slike, okrasni predmeti, rože, senčniki in pohištvo na terasi ter material, zložen ob kolibi na posnetku iz zraka. Kjer je bil predmet odstranjen, del prta in stola, ki ga je zakrival, ni bil fotografiran: model ga je verodostojno rekonstruiral. Prav tako je v 13 majhnih slikah, povečanih z umetno inteligenco, drobne podrobnosti (lesno strukturo, listje, rože, strešnike, kamne, majhne predmete) model rekonstruiral, ne obnovil: v polni velikosti so drobne podrobnosti verjetne, ne pa dokumentarne. Drugega niso spreminjali: mere, odprtine, tramovi, tla, pohištvo, ograje, pot, streha in sončni paneli so takšni, kot so bili fotografirani, pogledi skozi okna so isti, letni čas je tisti s posnetka (fotografija 24 je jesenska), na pravi nočni fotografiji (št. 26) pa so zvezde tiste, ki so bile posnete: 12 šibkih pik, ki jih je dodal model, je bilo odstranjenih. Na fotografijah niso bile ugotovljene pomanjkljivosti, ki bi jih bilo treba dokumentirati, in nobena ni bila omiljena ali skrita: gole lise na travniku so ostale. Zadnje štiri fotografije (27–30) so simulacije, označene na sliki: isti pogledi v svetlobi, ki je ni bilo (dva zlata večera, sončni zahod, noč s prižganimi okni). Hiša, zemljišče, drevesa, ograje in gore so isti; spremenita se svetloba in nebo, ponoči pa svetijo le štiri okna na pročelju in obstoječa luč na zatrepu. Ostalih 6 fotografij je bilo le lokalno popravljenih v svetlobi in barvah, brez generativne umetne inteligence (dva pogleda, št. 7 in 25, sta bila poleg tega povečana brez umetne inteligence). Svetloba in barve so bile popravljene kot pri običajni obdelavi fotografij. Neobdelane izvirne fotografije si lahko ogledate, če odprete fotografijo in pritisnete »Poglej izvirnik«; ogled ostaja edino merilo za dejansko stanje koče."
  ]
 }
};
